language: python
python:
  - 2.7

addons:
  apt:
    packages:
      - memcached
      - cython

install:
  - pip install -r requirements.txt
  - python setup.py install

before_script:
  - ./manage.py db upgrade

script:
  - py.test tests
